spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://----.----.----.----:3306/hbhims_pro?useTimezone=true&serverTimezone=GMT%2B8
    username: ----
    password: ----
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: warn
    com.example.hbhims: info
  file:
    path: ./logs
    name: hbhims_pro.log
